Stat svc
stanislavma/java-explore-with-me pull request #1
Opened 2024-07-28 22:10 UTC by stanislavma

2024-07-29 08:30 UTC, TomattmanYandex requested changes
Привет. Тут я как то запутался, поэтому до конца не посмотрел, и пишу общий комментарий
Есть два сервера (сервиса) Main и Stats 
Main основной, который выполняет всю работу и посылает статистику на Stats
Stats отвечает за хранение статистики и ее возврат

Каждый из этих сервисов по сути является одним отдельным приложением
В Main пока что нужно сделать только клиент, который будет уметь ходить в Stats сервер

Stats это  второе приложение которое должно состоятть из нескольких модулей
весь Stats сервер должен содержать только один контроллер который сохраняет значения статистики и возвращает их
И клиент должен уметь работать именно с этим контроллером
И когда приходит запрос на контроллер, контроллер не должен дергать клиент и идти к другому контроллеру, он должен вызвать метод сервиса и получить все данные оттуда

2024-07-29 08:30 UTC, TomattmanYandex commented on stats-service-parent/stats-client/src/main/java/ru/practicum/stats/client/StatsClientController.java
> +public class StatsClientController {
Клиент это то, что делает запросы, поэтому в имени не стоит указывать это
лучше переименовать в StatsController
А StatsClient - это то что умеет делать запросы либо d Stats сервер либо на конкретный Stats Контроллер

2024-07-29 08:30 UTC, TomattmanYandex commented on stats-service-parent/stats-service/src/main/java/ru/practicum/stats/service/StatsController.java
> +                .map(endpointHit -> EndpointHitDtoMapper
я бы порекомендовал в маппере перегрузить метод toViewStatsDto на то чтобы они принимал список и возвращал список, и эту логику сделать в этом методе, так получится что вся логика по маппингу будет находиться в одном месте

2024-07-29 08:30 UTC, TomattmanYandex commented on stats-service-parent/stats-service/src/main/java/ru/practicum/stats/service/StatsRepository.java
> +package ru.practicum.stats.service;
почему контроллер и репозиторий в одном пакете а сервис в другом,
стоит или все в один пакет положить (разделение по домену) или стоит все в разные (разделение по слоям)

2024-07-29 08:30 UTC, TomattmanYandex commented on stats-service-parent/stats-service/src/main/java/ru/practicum/stats/service/model/EndpointHit.java
> +    private Long hits;
зачем тут эта переменная?

2024-07-29 08:30 UTC, TomattmanYandex commented on stats-service-parent/stats-service/src/main/java/ru/practicum/stats/service/service/StatsServiceImpl.java
> +    public static List<String> cleanList(List<String> uriList) {
если этот метод используется только в этом классе, то зачем его делать публичным?
и я все еще не понимаю зачем этот метод нужен

2024-07-29 16:31 UTC, stanislavma commented on stats-service-parent/stats-service/src/main/java/ru/practicum/stats/service/model/EndpointHit.java
> +    private Long hits;
Long hits используется для хранения количества просмотров, когда делается запрос с помощью проекции с конструктором функция COUNT(s) передает значение в конструктор и далее как раз я сохраняю кол-воь просмотров в hits. Пробовал по разному сделать через обычный query, но что-то не получалось, нашел такой способ

2024-07-29 17:03 UTC, stanislavma commented
Спасибо за комментарии. Вроде понял что лишний контроллер в сервисе stats-client и по другим моментам тоже.
Мне еще не очень нравится, что сервис dto лежит в статистике, нельзя его в корне проекта  держать, на одном уровне с основными двумя сервисами?

2024-07-30 07:58 UTC, TomattmanYandex reviewed
Привет
по поводу твоего вопроса, лучше оставить так как есть, так другие сервисы смогут себе импортнуть как библиотечку, в которой будет минимум дтошек, ибо иначе будет вероятность того что будут не нужные данные импортиться, а зачем это?
ПО поводу комента в коде, приму так, но не забудь удалить этот контроллер из основного сервиса к следующей итерации

2024-07-30 07:58 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/stats/client/MainController.java
> +    public ResponseEntity<?> getEvents(HttpServletRequest request) {
тут тоже не должно быть этого контроллера, тут будут другие контроллеры и сервисы со своей логикой, и они между делом будут через клиент посылать статистику на другой сервис

2024-07-31 17:18 UTC, merged