Main svc
stanislavma/java-explore-with-me pull request #2
Opened 2024-08-04 21:58 UTC by stanislavma

2024-08-05 11:19 UTC, tomattman requested changes
Привет, пара мелочей есть на поправить

2024-08-05 11:19 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/controller/admin/CategoryAdminController.java
> +        Category updatedCategory = categoryService.update(catId, category);
чтобы не плодить дополнительных сущностей можно сразу в мапер передавать результат выполнения 
return CategoryMapper.toDto(categoryService.update(catId, category));

2024-08-05 11:19 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/controller/admin/CategoryAdminController.java
> +        Category updatedCategory = categoryService.update(catId, category);
ну так в принципе во всех методах

2024-08-05 11:19 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/controller/admin/CategoryAdminController.java
> +        Category updatedCategory = categoryService.update(catId, category);
это не ошибка, а так, мини оптимизация

2024-08-05 11:19 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/controller/admin/CompilationAdminController.java
> +//    @Transactional
закомментированный код не допускается

2024-08-05 11:19 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/controller/pub/EventPublicController.java
> +            @RequestParam(required = false) String text,
когда так много параметров их можно тоже обернуть в dto и принимать dto

2024-08-05 11:19 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/dto/CategoryDto.java
> +public class CategoryDto {
Лучше разделить по пакетам по функционалу, а то сейчас такое количество дтох в одном месте пугает

2024-08-05 14:53 UTC, stanislavma commented
Привет. Оптимизировал по твоим комментариям. Спасибо за ревью.

2024-08-06 07:47 UTC, tomattman approved these changes
Принято

2024-08-06 07:47 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/controller/admin/CategoryAdminController.java
> +        return CategoryMapper.toDto(categoryService.update(catId, category));
можно вообще сделать веселую строку, но читаться она будет не очень
 return CategoryMapper.toDto(categoryService.update(catId, CategoryMapper.toEntity(categoryDto)));

2024-08-06 14:34 UTC, merged