Feature comments
stanislavma/java-explore-with-me pull request #3
Opened 2024-08-10 12:17 UTC by stanislavma

2024-08-11 11:09 UTC, tomattman requested changes
Привет, все хорошо, одну мелочь откоментировал, можешь ее посмотреть, но главное
не прошла сборка проекта гитхабом, надо выяснить почему и поправить

2024-08-11 11:09 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/controller/authorized/CommentPrivateController.java
> +@RequestMapping("/users/{userId}/comments")
интересная связка, 
если привязывать коменты к пользователю то подходит именно такая
Если привязывать коменты к ивенту, то лучше сменитьь немного путь

2024-08-11 11:09 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/controller/authorized/CommentPrivateController.java
> +@RequestMapping("/users/{userId}/comments")
но текущая версия очень неконсистентна с публичным контроллером, там все идет через привязку к ивенту, а тут к юзеру,
обычно получение и создание идут примерно по одному пути

2024-08-11 16:41 UTC, stanislavma commented on main-service/src/main/java/ru/practicum/ewm/controller/authorized/CommentPrivateController.java
> +@RequestMapping("/users/{userId}/comments")
Привет. Я пытался сейчас переделать через event, но в итоге вспомнил почему я сделал через user... через event возникает проблема - для обновления и удаления комментария не нужно событие, а только id комментария. А для других endpoint везде нужен userId, поэтому я сделал через /users/{userId}/comments.
Пробовал сделать просто через /comments, но при таком раскладе тоже не очен получается, т.к. для обновления и удаления нужно передавать commentId, а для добавления не нужно и структура ломается. Как-то не очень получается, как не крути. Поэтому оставил пока.

2024-08-12 07:55 UTC, tomattman approved these changes
Принято

2024-08-12 09:11 UTC, merged

2024-08-12 09:11 UTC, stanislavma commented
Спасибо!